import type { Metadata } from "next";
import "../styles/globals.css";
import "../../public/fonts/style.css";
import Image from "next/image";
import MainLogo from "../../public/assets/images/logo-league.png";
import Link from "next/link";
// import { AuthButton } from "@/components/AuthButton";
import Champions from "@/components/headerIcon/Champions";
import Items from "@/components/headerIcon/Items";
import Rotation from "@/components/headerIcon/Rotation";

export const metadata: Metadata = {
  title: "리그 오브 레전드 정보 앱",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-[100%]">
      <body>
        <header className="fixed bg-[#0b141e] w-full flex py-5 px-10 items-center justify-between z-10">
          <Link href="/" className="flex items-center">
            <Image src={MainLogo} alt="리그오브레전드 로고" width={50} height={50} />
            <h1 className="text-[#c79a3b] font-bold text-[1.5rem]">League Of Legends</h1>
          </Link>
          <div className="flex gap-8">
            <Link href="/champions">
              <Champions />
            </Link>
            <Link href="/items">
              <Items />
            </Link>
            <Link href="/rotation">
              <Rotation />
            </Link>
            {/* <AuthButton /> */}
          </div>
        </header>
        <div>{children}</div>
        <footer className="fixed bottom-0 w-full p-4 text-center bg-[#0b141e] z-10">
          <p className="max-w-[1500px] mx-auto text-white text-[0.875rem]">
            lol-dex is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone
            officially involved in producing or managing Riot Games properties. Riot Games and all associated properties
            are trademarks or registered trademarks of Riot Games, Inc.
          </p>
        </footer>
      </body>
    </html>
  );
}
